baseURL = 'https://zenshin.blog'
languageCode = 'en-us'
title = "Zenia Hew | zenshin "
theme = 'zenshin-impact'
enableRobotsTXT = true

[markup]
    [markup.highlight]
        codeFences = true 
        guessSyntax = false 
        lineNos = false 
        noClasses = false

[[menus.main]]
name = '𖠿'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About me'
pageRef = '/about'
weight = 20


